# Generated by Django 5.1.5 on 2025-02-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikasi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='jurusan',
            field=models.CharField(default='rpl', max_length=50),
        ),
    ]
